title: "Make maps better, **together**."
description: "Collaborative mapping and the Open Source Way"

exclude:
  - script
  - ".gitignore"
  - Gemfile
  - Gemfile.lock
  - readme.md
  - node_modules
  - ".sass-cache"
  - "package.json"
  - "*.scss"
  - "*.coffee"
pygments: true
markdown: kramdown
excerpt_separator: ""
